{% set version = "24.1.0" %}

# handle undefined PYTHON in `noarch: generic` outputs
{% if PYTHON is not defined %}{% set PYTHON = "$PYTHON" %}{% endif %}

package:
  name: service-identity-build
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/service-identity/service_identity-{{ version }}.tar.gz
  sha256: 6829c9d62fb832c2e1c435629b0a8c476e1929881f28bee4d20bc24161009221

build:
  noarch: python
  number: 0

outputs:
  - name: service-identity
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    requirements:
      host:
        - hatch-fancy-pypi-readme
        - hatch-vcs
        - hatchling
        - pip
        - python >=3.8
      run:
        - attrs >=19.1.0
        - cryptography
        - pyasn1
        - pyasn1-modules
        - python >=3.8
    test:
      source_files:
        - tests
      requires:
        - coverage
        - pip
        - pytest
      imports:
        - service_identity
      commands:
        - pip check
        - coverage run --source=service_identity --branch -m pytest -vv --tb=long --color=yes
        - coverage report --show-missing --skip-covered --fail-under=100

  - name: service_identity
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('service-identity', max_pin="x.x.x") }}
    test:
      imports:
        - service_identity

about:
  home: https://github.com/pyca/service-identity
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Service identity verification for pyOpenSSL.
  description: |
    service_identity aspires to give you all the tools you need for verifying
    whether a certificate is valid for the intended purposes.
  doc_url: https://service-identity.readthedocs.io/en/stable/
  dev_url: https://github.com/pyca/service-identity

extra:
  feedstock-name: service_identity
  recipe-maintainers:
    - isuruf
    - bollwyvl
