{% set name = "service-identity" %}
{% set version = "24.1.0" %}

package:
  name: {{ name|lower }}-build
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6829c9d62fb832c2e1c435629b0a8c476e1929881f28bee4d20bc24161009221

build:
  noarch: python
  number: 0

outputs:
  - name: service-identity
    script: build_base.sh
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python >=2.7
        - setuptools >=40.6.0
      run:
        - attrs >=19.1.0
        - cryptography
        - pyasn1
        - pyasn1-modules
        - pyopenssl >=0.12
        - python >=2.7
        - six
    test:
      imports:
        - service_identity

  - name: service_identity
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('service-identity', max_pin="x.x.x") }}
    test:
      imports:
        - service_identity

about:
  home: https://github.com/pyca/service-identity
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Service identity verification for pyOpenSSL.
  description: |
    service_identity aspires to give you all the tools you need for verifying
    whether a certificate is valid for the intended purposes.
  doc_url: https://service-identity.readthedocs.io/en/stable/
  dev_url: https://github.com/pyca/service-identity

extra:
  feedstock-name: service_identity
  recipe-maintainers:
    - isuruf
